favicon: /assets/icon/favicon.ico

# --------------------
# Navbar
# --------------------
navbar:
  logo: /assets/icon/android-chrome-96x96.png
  logo_text: 'Theme Cards'
  links:
    zh-CN:
      - logo: fab fa-github
        text: '主题源码'
        url: 'https://github.com/ChrAlpha/hexo-theme-cards'
      - logo: 
        text: '使用文档'
        url: 'https://github.com/ChrAlpha/theme-cards-docs'
      - logo: 
        text: '主题 Demo'
        url: 'https://theme-cards.ichr.me/demo/'

# --------------------
# Sidebar Items
# --------------------
sidebar:
  zh-CN: # Language
    docs: # Type bname
      level: 1 # 1 or 2
      items:
        - 开始使用 | start/
        - 基本配置 | config/
        - 页面配置 | pages/
        - 第三方服务 | third-party/
        - 拓展插件 | expand/
        - 开始创作 | write/
    changelog: # 另一个文档类型，以下配置的侧边栏内容只会在 zh-CN 语言、类型为「changelog」的页面下显示
      level: 1 # 一级侧边栏
      items:
        - 0.1.0 | changelog/newest.html # 一级侧边栏不包括子菜单，只包括链接
        

github:
  repo: ChrAlpha/theme-cards-docs
  edit_on_github: enable # true / false
