name: Theme Cards Docs CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Generate Site
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npm run build

          mkdir -p ./dist
          cp -rf ./public/. ./dist

          git clone --depth=1 https://github.com/ChrAlpha/theme-cards-demo.git demo
          git clone --depth=1 https://github.com/ChrAlpha/hexo-theme-cards.git ./demo/themes/cards
          if [ -f ./demo/package-lock.json ]; then npm --prefix ./demo ci; else npm --prefix ./demo install; fi
          npm --prefix ./demo run build
          mkdir -p ./dist/demo
          cp -rf ./demo/public/. ./dist/demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          external_repository: ChrAlpha/theme-cards-site
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: theme-cards.ichr.me
          allow_empty_commit: true
          force_orphan: true
